<?php

namespace Tusk\Web\Router;

use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use ReflectionClass;
use ReflectionException;
use SplFileInfo;
use Throwable;
use Tusk\Web\Attribute\Route;

class RouteCompiler
{
    /**
     * @param array<string> $directories
     * @return array<string, array<string, array{class: string, method: string, middleware: array}>>
     */
    public function scan(array $directories): array
    {
        $routes = [
            'GET' => [],
            'POST' => [],
            'PUT' => [],
            'PATCH' => [],
            'DELETE' => [],
            'OPTIONS' => [],
        ];

        foreach ($directories as $path) {
            $files = [];
            if (is_file($path)) {
                $files[] = new SplFileInfo($path);
            } elseif (is_dir($path)) {
                $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path));
                foreach ($iterator as $file) {
                    $files[] = $file;
                }
            }

            /** @var SplFileInfo $file */
            foreach ($files as $file) {
                if ($file->isFile() && $file->getExtension() === 'php') {
                    $className = $this->extractClassName($file->getPathname());
                    
                    if ($className) {
                        try {
                            if (!class_exists($className)) {
                                require_once $file->getPathname();
                            }
                            
                            $reflection = new ReflectionClass($className);
                            if ($reflection->isInstantiable()) {
                                foreach ($reflection->getMethods() as $method) {
                                    $attributes = $method->getAttributes(Route::class);
                                    
                                    foreach ($attributes as $attribute) {
                                        /** @var Route $route */
                                        $route = $attribute->newInstance();
                                        
                                        $routeInfo = [
                                            'class' => $className,
                                            'method' => $method->getName(),
                                            'middleware' => $route->middleware,
                                        ];
                                        
                                        foreach ((array)$route->methods as $httpMethod) {
                                            $httpMethod = strtoupper($httpMethod);
                                            $quotedPath = preg_quote($route->path, '#');
                                            $pattern = preg_replace('/\\\\\{([a-zA-Z0-9_]+)\\\\\}/', '(?P<$1>[^/]+)', $quotedPath);
                                            $pattern = '#^' . $pattern . '$#';
                                            
                                            $routes[$httpMethod][$pattern] = $routeInfo;
                                        }
                                    }
                                }
                            }
                        } catch (ReflectionException $e) {
                            // ignore
                        } catch (Throwable $e) {
                            // ignore
                        }
                    }
                }
            }
        }

        return $routes;
    }

    public function compile(array $routes, string $namespace = 'Tusk\Compiled', string $className = 'CompiledRouter'): string
    {
        $code = "<?php\n\n";
        $code .= "namespace $namespace;\n\n";
        $code .= "use Tusk\\Web\\Router\\RouterInterface;\n";
        $code .= "use Tusk\\Web\\Router\\RouteMatch;\n\n";
        
        $code .= "/**\n * Auto-generated by Tusk RouteCompiler.\n */\n";
        $code .= "class $className implements RouterInterface\n{\n";
        
        $code .= "    public function match(string \$method, string \$uri): ?RouteMatch\n    {\n";
        $code .= "        \$method = strtoupper(\$method);\n";
        
        $code .= "        switch (\$method) {\n";
        foreach ($routes as $httpMethod => $paths) {
            if (empty($paths)) continue;
            
            $code .= "            case '$httpMethod':\n";
            foreach ($paths as $pattern => $info) {
                $class = $info['class'];
                $methodName = $info['method'];
                $middleware = var_export($info['middleware'], true);
                
                $code .= "                if (preg_match('$pattern', \$uri, \$matches)) {\n";
                $code .= "                    \$params = array_filter(\$matches, 'is_string', ARRAY_FILTER_USE_KEY);\n";
                $code .= "                    return new RouteMatch('$class', '$methodName', \$params, $middleware);\n";
                $code .= "                }\n";
            }
            $code .= "                break;\n";
        }
        $code .= "        }\n\n";
        
        $code .= "        return null;\n";
        $code .= "    }\n";
        $code .= "}\n";
        
        return $code;
    }

    public function compileAndDump(array $directories, string $outputPath, string $namespace = 'Tusk\Compiled', string $className = 'CompiledRouter'): void
    {
        $map = $this->scan($directories);
        $code = $this->compile($map, $namespace, $className);
        
        $dir = dirname($outputPath);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }
        
        file_put_contents($outputPath, $code);
    }

    private function extractClassName(string $file): ?string
    {
        $buffer = file_get_contents($file);
        if (!$buffer) return null;
        
        $tokens = token_get_all($buffer);
        $namespace = '';
        $class = '';
        
        for ($i = 0; $i < count($tokens); $i++) {
            if (is_array($tokens[$i]) && $tokens[$i][0] === T_NAMESPACE) {
                for ($j = $i + 1; $j < count($tokens); $j++) {
                    if (is_array($tokens[$j]) && ($tokens[$j][0] === T_NAME_QUALIFIED || $tokens[$j][0] === T_STRING)) {
                        $namespace .= $tokens[$j][1];
                    } else if ($tokens[$j] === ';' || $tokens[$j] === '{') {
                        break;
                    }
                }
            }
            if (is_array($tokens[$i]) && $tokens[$i][0] === T_CLASS) {
                for ($j = $i + 1; $j < count($tokens); $j++) {
                    if ($tokens[$j] === '{') {
                        $class = is_array($tokens[$i + 2]) ? $tokens[$i + 2][1] : '';
                        break 2;
                    }
                }
            }
        }
        
        return $class ? ($namespace ? $namespace . '\\' . $class : $class) : null;
    }
}
