<?php

namespace Tusk\Cli;

use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use ReflectionClass;
use ReflectionException;
use SplFileInfo;
use Throwable;
use Tusk\Cli\Attribute\AsCommand;

class CommandCompiler
{
    /**
     * @param array<string> $directories
     * @return array<string, array{class: string, description: string}>
     */
    public function scan(array $directories): array
    {
        $commands = [];

        foreach ($directories as $path) {
            $files = [];
            if (is_file($path)) {
                $files[] = new SplFileInfo($path);
            } elseif (is_dir($path)) {
                $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path));
                foreach ($iterator as $file) {
                    $files[] = $file;
                }
            }

            /** @var SplFileInfo $file */
            foreach ($files as $file) {
                if ($file->isFile() && $file->getExtension() === 'php') {
                    $className = $this->extractClassName($file->getPathname());
                    
                    if ($className) {
                        try {
                            if (!class_exists($className)) {
                                require_once $file->getPathname();
                            }
                            
                            $reflection = new ReflectionClass($className);
                            if ($reflection->isInstantiable()) {
                                $attributes = $reflection->getAttributes(AsCommand::class);
                                foreach ($attributes as $attribute) {
                                    /** @var AsCommand $cmd */
                                    $cmd = $attribute->newInstance();
                                    
                                    $commands[$cmd->name] = [
                                        'class' => $className,
                                        'description' => $cmd->description,
                                    ];
                                }
                            }
                        } catch (ReflectionException $e) {
                        } catch (Throwable $e) {
                        }
                    }
                }
            }
        }

        return $commands;
    }

    public function compile(array $commands, string $namespace = 'Tusk\Compiled', string $className = 'CompiledCommandRegistry'): string
    {
        $code = "<?php\n\n";
        $code .= "namespace $namespace;\n\n";
        
        $code .= "/**\n * Auto-generated by Tusk CommandCompiler.\n */\n";
        $code .= "class $className\n{\n";
        $code .= "    public static function getCommands(): array\n    {\n";
        $code .= "        return [\n";
        
        foreach ($commands as $name => $info) {
            $class = $info['class'];
            $desc = addslashes($info['description']);
            $code .= "            '$name' => ['class' => '$class', 'description' => '$desc'],\n";
        }
        
        $code .= "        ];\n";
        $code .= "    }\n";
        $code .= "}\n";
        
        return $code;
    }

    public function compileAndDump(array $directories, string $outputPath, string $namespace = 'Tusk\Compiled', string $className = 'CompiledCommandRegistry'): void
    {
        $map = $this->scan($directories);
        $code = $this->compile($map, $namespace, $className);
        
        $dir = dirname($outputPath);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }
        
        file_put_contents($outputPath, $code);
    }

    private function extractClassName(string $file): ?string
    {
        $buffer = file_get_contents($file);
        if (!$buffer) return null;
        
        $tokens = token_get_all($buffer);
        $namespace = '';
        $class = '';
        
        for ($i = 0; $i < count($tokens); $i++) {
            if (is_array($tokens[$i]) && $tokens[$i][0] === T_NAMESPACE) {
                for ($j = $i + 1; $j < count($tokens); $j++) {
                    if (is_array($tokens[$j]) && ($tokens[$j][0] === T_NAME_QUALIFIED || $tokens[$j][0] === T_STRING)) {
                        $namespace .= $tokens[$j][1];
                    } else if ($tokens[$j] === ';' || $tokens[$j] === '{') {
                        break;
                    }
                }
            }
            if (is_array($tokens[$i]) && $tokens[$i][0] === T_CLASS) {
                for ($j = $i + 1; $j < count($tokens); $j++) {
                    if ($tokens[$j] === '{') {
                        $class = is_array($tokens[$i + 2]) ? $tokens[$i + 2][1] : '';
                        break 2;
                    }
                }
            }
        }
        
        return $class ? ($namespace ? $namespace . '\\' . $class : $class) : null;
    }
}
