<?php

namespace Tusk\Core\Container;

class ContainerCompiler
{
    /**
     * Compiles definitions into a PHP class string.
     *
     * @param array<string, array> $definitions
     * @param string $namespace
     * @param string $className
     * @return string
     */
    public function compile(array $definitions, string $namespace = 'Tusk\Compiled', string $className = 'CompiledContainer'): string
    {
        $code = "<?php\n\n";
        $code .= "namespace $namespace;\n\n";
        $code .= "use Psr\\Container\\ContainerInterface;\n";
        $code .= "use Tusk\\Contracts\\Container\\ContainerInterface as TuskContainerInterface;\n";
        $code .= "use RuntimeException;\n";
        $code .= "use ReflectionClass;\n\n";
        
        $code .= "/**\n * This class is auto-generated by Tusk ContainerCompiler.\n * DO NOT EDIT.\n */\n";
        $code .= "class $className implements TuskContainerInterface, ContainerInterface\n{\n";
        
        $code .= "    private array \$singletonInstances = [];\n";
        $code .= "    private array \$requestInstances = [];\n\n";

        $code .= "    public function instance(string \$id, object \$instance): void\n    {\n";
        $code .= "        \$this->singletonInstances[\$id] = \$instance;\n    }\n\n";
        
        $code .= "    public function get(string \$id): object\n    {\n";
        $code .= "        if (isset(\$this->singletonInstances[\$id])) {\n";
        $code .= "            return \$this->singletonInstances[\$id];\n";
        $code .= "        }\n\n";
        
        $code .= "        if (isset(\$this->requestInstances[\$id])) {\n";
        $code .= "            return \$this->requestInstances[\$id];\n";
        $code .= "        }\n\n";
        
        $code .= "        return match (\$id) {\n";
        $code .= "            TuskContainerInterface::class => \$this,\n";
        $code .= "            ContainerInterface::class => \$this,\n";
        
        $aliasMap = [];
        foreach ($definitions as $id => $def) {
            $class = $def['class'];
            $provides = $def['provides'] ?? $class;
            $code .= "            '$provides' => \$this->resolve_{$this->sanitizeName($class)}(),\n";
            
            // If it's a factory, we don't alias the factory's own class to itself automatically 
            // unless requested. We alias its interfaces.
            foreach ($def['interfaces'] as $interface) {
                // Last registered class for an interface wins
                $aliasMap[$interface] = $provides;
            }
        }
        
        foreach ($aliasMap as $interface => $provides) {
            $code .= "            '$interface' => \$this->get('$provides'),\n";
        }
        
        $code .= "            default => throw new RuntimeException(\"Service not found: \$id\"),\n";
        $code .= "        };\n";
        $code .= "    }\n\n";
        
        // Factory methods
        foreach ($definitions as $id => $def) {
            $class = $def['class'];
            $provides = $def['provides'] ?? $class;
            $isFactory = $def['is_factory'] ?? false;
            $scope = $def['scope'];
            $deps = $def['dependencies'];
            
            $depString = implode(', ', array_map(fn($d) => "\$this->get('$d')", $deps));
            $methodName = "resolve_" . $this->sanitizeName($class);
            
            $code .= "    private function {$methodName}(): object\n    {\n";
            if ($isFactory) {
                $code .= "        \$factory = new \\$class($depString);\n";
                $code .= "        try {\n";
                $code .= "            \$instance = \$factory();\n";
                $code .= "        } catch (\Throwable \$e) {\n";
                $code .= "            throw new RuntimeException(\"Error in factory $class: \" . \$e->getMessage(), 0, \$e);\n";
                $code .= "        }\n";
            } else {
                $code .= "        \$instance = new \\$class($depString);\n";
            }
            
            if ($scope === 'singleton') {
                $code .= "        \$this->singletonInstances['$provides'] = \$instance;\n";
            } elseif ($scope === 'request') {
                $code .= "        \$this->requestInstances['$provides'] = \$instance;\n";
            }
            
            $code .= "        return \$instance;\n";
            $code .= "    }\n\n";
        }
        
        // has()
        $code .= "    public function has(string \$id): bool\n    {\n";
        $code .= "        return in_array(\$id, [\n";
        
        $allIds = array_unique(array_merge(
            array_column($definitions, 'provides'),
            array_keys($aliasMap)
        ));
        foreach ($allIds as $id) {
            $code .= "            '$id',\n";
        }
        
        $code .= "        ]);\n";
        $code .= "    }\n\n";
        
        // resetScope()
        $code .= "    public function resetScope(string \$scope): void\n    {\n";
        $code .= "        if (\$scope === 'request') {\n";
        $code .= "            \$this->requestInstances = [];\n";
        $code .= "        }\n";
        $code .= "    }\n\n";
        
        // runHooks()
        $code .= "    public function runHooks(string \$attributeClass): void\n    {\n";
        $code .= "        foreach (\$this->singletonInstances as \$instance) {\n";
        $code .= "            \$this->executeHooksOn(\$instance, \$attributeClass);\n";
        $code .= "        }\n";
        $code .= "        foreach (\$this->requestInstances as \$instance) {\n";
        $code .= "            \$this->executeHooksOn(\$instance, \$attributeClass);\n";
        $code .= "        }\n";
        $code .= "    }\n\n";
        
        $code .= "    private function executeHooksOn(object \$instance, string \$attributeClass): void\n    {\n";
        $code .= "        \$reflection = new ReflectionClass(\$instance);\n";
        $code .= "        foreach (\$reflection->getMethods() as \$method) {\n";
        $code .= "            if (!empty(\$method->getAttributes(\$attributeClass))) {\n";
        $code .= "                \$method->invoke(\$instance);\n";
        $code .= "            }\n";
        $code .= "        }\n";
        $code .= "    }\n";
        $code .= "}\n";
        
        return $code;
    }
    
    private function sanitizeName(string $name): string
    {
        return str_replace('\\', '_', $name);
    }
}
