<?php

namespace Tusk\Core\Container;

class ContainerCompiler
{
    /**
     * Compiles definitions into a PHP class string.
     *
     * @param array<string, array> $definitions
     */
    public function compile(array $definitions, string $namespace = 'Tusk\\Compiled', string $className = 'CompiledContainer'): string
    {
        $code = "<?php\n\n";
        $code .= "namespace $namespace;\n\n";
        $code .= "use Psr\\Container\\ContainerInterface;\n";
        $code .= "use Tusk\\Contracts\\Container\\ContainerInterface as TuskContainerInterface;\n";
        $code .= "use RuntimeException;\n\n";
        $code .= "/**\n * This class is auto-generated by Tusk ContainerCompiler.\n * DO NOT EDIT.\n */\n";
        $code .= "class $className implements TuskContainerInterface, ContainerInterface\n{\n";
        $code .= "    private array \$singletonInstances = [];\n";
        $code .= "    private array \$workerInstances = [];\n";
        $code .= "    private array \$requestInstances = [];\n\n";

        $code .= "    public function instance(string \$id, object \$instance): void\n    {\n";
        $code .= "        \$this->singletonInstances[\$id] = \$instance;\n    }\n\n";

        $code .= "    public function get(string \$id): object\n    {\n";
        $code .= "        if (isset(\$this->singletonInstances[\$id])) {\n";
        $code .= "            return \$this->singletonInstances[\$id];\n        }\n\n";
        $code .= "        if (isset(\$this->workerInstances[\$id])) {\n";
        $code .= "            return \$this->workerInstances[\$id];\n        }\n\n";
        $code .= "        if (isset(\$this->requestInstances[\$id])) {\n";
        $code .= "            return \$this->requestInstances[\$id];\n        }\n\n";
        $code .= "        return match (\$id) {\n";
        $code .= "            TuskContainerInterface::class => \$this,\n";
        $code .= "            ContainerInterface::class => \$this,\n";

        $aliasMap = [];
        foreach ($definitions as $def) {
            $class = $def['class'];
            $provides = $def['provides'] ?? $class;
            $code .= '            '.var_export($provides, true)." => \$this->resolve_{$this->sanitizeName($class)}(),\n";

            foreach ($def['interfaces'] ?? [] as $interface) {
                $aliasMap[$interface] = $provides;
            }
        }

        foreach ($aliasMap as $interface => $provides) {
            $code .= '            '.var_export($interface, true)." => \$this->get(".var_export($provides, true)."),\n";
        }

        $code .= "            default => throw new RuntimeException(\"Service not found: \$id\"),\n";
        $code .= "        };\n    }\n\n";

        foreach ($definitions as $def) {
            $class = $def['class'];
            $provides = $def['provides'] ?? $class;
            $isFactory = $def['is_factory'] ?? false;
            $scope = $def['scope'] ?? 'singleton';
            $deps = $def['dependencies'] ?? [];
            $depString = implode(', ', array_map(static fn (string $dependency): string => '\$this->get('.var_export($dependency, true).')', $deps));
            $methodName = 'resolve_'.$this->sanitizeName($class);

            $code .= "    private function {$methodName}(): object\n    {\n";
            $cache = match ($scope) {
                'worker' => 'workerInstances',
                'request' => 'requestInstances',
                'singleton' => 'singletonInstances',
                default => null,
            };

            if ($cache !== null) {
                $key = $this->escapeSingleQuoted($provides);
                $code .= "        if (isset(\$this->{$cache}['{$key}'])) {\n";
                $code .= "            return \$this->{$cache}['{$key}'];\n        }\n";
            }

            if ($isFactory) {
                $code .= "        \$factory = new \\$class($depString);\n";
                $code .= "        try {\n";
                $code .= "            \$instance = \$factory();\n";
                $code .= "        } catch (\\Throwable \\$e) {\n";
                $code .= "            throw new RuntimeException(\"Error in factory $class: \" . \$e->getMessage(), 0, \\$e);\n";
                $code .= "        }\n";
            } else {
                $code .= "        \$instance = new \\$class($depString);\n";
            }

            if ($cache !== null) {
                $code .= "        \$this->{$cache}['{$key}'] = \$instance;\n";
            }

            $code .= "        return \$instance;\n    }\n\n";
        }

        $code .= "    public function has(string \$id): bool\n    {\n";
        $code .= "        return in_array(\$id, [\n";
        $allIds = array_unique(array_merge(
            array_map(static fn (array $definition): string => $definition['provides'] ?? $definition['class'], $definitions),
            array_keys($aliasMap),
        ));
        foreach ($allIds as $id) {
            $code .= '            '.var_export($id, true).",\n";
        }
        $code .= "        ], true);\n    }\n\n";

        $code .= "    public function resetScope(string \$scope): void\n    {\n";
        $code .= "        if (\$scope === 'worker') {\n            \$this->workerInstances = [];\n        }\n";
        $code .= "        if (\$scope === 'request') {\n            \$this->requestInstances = [];\n        }\n";
        $code .= "    }\n\n";

        $code .= "    public function runLifecycleHooks(string \$event): void\n    {\n";
        $code .= "        \$firstFailure = null;\n";
        foreach ($this->compileHookCalls($definitions) as $event => $calls) {
            $code .= '        if ($event === '.var_export($event, true).") {\n";
            foreach ($calls as [$class, $method]) {
                $code .= "            try {\n";
                $code .= "                \$this->resolve_{$this->sanitizeName($class)}()->".$this->escapeMethod($method)."();\n";
                $code .= "            } catch (\\Throwable \$exception) {\n";
                $code .= "                \$firstFailure ??= \$exception;\n";
                $code .= "            }\n";
            }
            $code .= "            if (\$firstFailure !== null) {\n                throw \$firstFailure;\n            }\n";
            $code .= "            return;\n        }\n";
        }
        $code .= "    }\n\n";

        $code .= "    public function runHooks(string \$attributeClass): void\n    {\n";
        $code .= "        \$event = match (\$attributeClass) {\n";
        $code .= "            'Tusk\\\\Contracts\\\\Attributes\\\\OnStart' => 'application.start',\n";
        $code .= "            'Tusk\\\\Contracts\\\\Attributes\\\\OnWorkerStart' => 'worker.start',\n";
        $code .= "            'Tusk\\\\Contracts\\\\Attributes\\\\OnWorkerStop' => 'worker.stop',\n";
        $code .= "            'Tusk\\\\Contracts\\\\Attributes\\\\OnRequestStart' => 'request.start',\n";
        $code .= "            'Tusk\\\\Contracts\\\\Attributes\\\\OnRequestEnd' => 'request.end',\n";
        $code .= "            'Tusk\\\\Contracts\\\\Attributes\\\\OnShutdown' => 'application.stop',\n";
        $code .= "            default => null,\n";
        $code .= "        };\n        if (\$event !== null) {\n            \$this->runLifecycleHooks(\$event);\n        }\n    }\n";
        $code .= "}\n";

        return $code;
    }

    /**
     * @param array<string, array> $definitions
     * @return array<string, list<array{0: string, 1: string}>>
     */
    private function compileHookCalls(array $definitions): array
    {
        $calls = [];

        foreach ($definitions as $definition) {
            $class = $definition['class'];
            foreach ($definition['hooks'] ?? [] as $event => $methods) {
                foreach ($methods as $method) {
                    $calls[$event][] = [$class, $method];
                }
            }
        }

        return $calls;
    }

    private function sanitizeName(string $name): string
    {
        return str_replace('\\', '_', $name);
    }

    private function escapeSingleQuoted(string $value): string
    {
        return str_replace(['\\', "'"], ['\\\\', "\\'"], $value);
    }

    private function escapeMethod(string $method): string
    {
        return preg_replace('/[^A-Za-z0-9_]/', '', $method) ?? $method;
    }
}
