<?php

namespace Tusk\Events\Compiler;

use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use ReflectionClass;
use ReflectionException;
use ReflectionNamedType;
use SplFileInfo;
use Throwable;
use Tusk\Events\Attributes\EventListener;

class EventCompiler
{
    /**
     * @param array<string> $directories
     * @return array<string, array<array{0: string, 1: string}>>
     */
    public function scan(array $directories): array
    {
        $listenerMap = [];

        foreach ($directories as $directory) {
            if (!is_dir($directory)) {
                continue;
            }

            $iterator = new RecursiveIteratorIterator(
                new RecursiveDirectoryIterator($directory)
            );

            /** @var SplFileInfo $file */
            foreach ($iterator as $file) {
                if ($file->isFile() && $file->getExtension() === 'php') {
                    $className = $this->extractClassName($file->getPathname());
                    
                    if ($className) {
                        try {
                            if (!class_exists($className) && !interface_exists($className)) {
                                require_once $file->getPathname();
                            }
                            
                            $reflection = new ReflectionClass($className);
                            if ($reflection->isInstantiable()) {
                                foreach ($reflection->getMethods() as $method) {
                                    $attributes = $method->getAttributes(EventListener::class);
                                    
                                    if (!empty($attributes)) {
                                        $params = $method->getParameters();
                                        if (count($params) > 0) {
                                            $eventType = $params[0]->getType();
                                            if ($eventType instanceof ReflectionNamedType && !$eventType->isBuiltin()) {
                                                $eventClass = $eventType->getName();
                                                $listenerMap[$eventClass][] = [$className, $method->getName()];
                                            }
                                        }
                                    }
                                }
                            }
                        } catch (ReflectionException $e) {
                            // ignore
                        } catch (Throwable $e) {
                            // ignore
                        }
                    }
                }
            }
        }

        return $listenerMap;
    }

    public function compile(array $listenerMap, string $namespace = 'Tusk\Compiled', string $className = 'CompiledListenerProvider'): string
    {
        $code = "<?php\n\n";
        $code .= "namespace $namespace;\n\n";
        $code .= "use Tusk\\Events\\ListenerProvider;\n";
        $code .= "use Tusk\\Contracts\\Container\\ContainerInterface;\n\n";
        
        $code .= "/**\n * Auto-generated by Tusk EventCompiler.\n */\n";
        $code .= "class $className extends ListenerProvider\n{\n";
        
        $code .= "    public function __construct(ContainerInterface \$container)\n    {\n";
        $code .= "        parent::__construct(\$container, [\n";
        
        foreach ($listenerMap as $eventClass => $listeners) {
            $code .= "            '$eventClass' => [\n";
            foreach ($listeners as $listener) {
                $service = $listener[0];
                $method = $listener[1];
                $code .= "                ['$service', '$method'],\n";
            }
            $code .= "            ],\n";
        }
        
        $code .= "        ]);\n";
        $code .= "    }\n";
        $code .= "}\n";
        
        return $code;
    }

    public function compileAndDump(array $directories, string $outputPath, string $namespace = 'Tusk\Compiled', string $className = 'CompiledListenerProvider'): void
    {
        $map = $this->scan($directories);
        $code = $this->compile($map, $namespace, $className);
        
        $dir = dirname($outputPath);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }
        
        file_put_contents($outputPath, $code);
    }

    private function extractClassName(string $file): ?string
    {
        $fp = fopen($file, 'r');
        if (!$fp) return null;
        
        $class = $namespace = $buffer = '';
        $i = 0;
        
        while (!$class) {
            if (feof($fp)) break;
            $buffer .= fread($fp, 512);
            $tokens = @token_get_all($buffer);
            if (!str_contains($buffer, '{')) continue;
            for (; $i < count($tokens); $i++) {
                if ($tokens[$i][0] === T_NAMESPACE) {
                    for ($j = $i + 1; $j < count($tokens); $j++) {
                        if ($tokens[$j][0] === T_NAME_QUALIFIED || $tokens[$j][0] === T_STRING) {
                            $namespace .= $tokens[$j][1];
                        } else if ($tokens[$j] === ';' || $tokens[$j] === '{') {
                            break;
                        }
                    }
                }
                if ($tokens[$i][0] === T_CLASS) {
                    for ($j = $i + 1; $j < count($tokens); $j++) {
                        if ($tokens[$j] === '{') {
                            $class = $tokens[$i + 2][1];
                            break 2;
                        }
                    }
                }
            }
        }
        fclose($fp);
        return $class ? ($namespace ? $namespace . '\\' . $class : $class) : null;
    }
}
