<?php

namespace Tusk\Compiled;

use Psr\Container\ContainerInterface;
use Tusk\Contracts\Container\ContainerInterface as TuskContainerInterface;
use RuntimeException;
use ReflectionClass;

/**
 * This class is auto-generated by Tusk ContainerCompiler.
 * DO NOT EDIT.
 */
class CompiledContainer implements TuskContainerInterface, ContainerInterface
{
    private array $singletonInstances = [];
    private array $requestInstances = [];

    public function get(string $id): object
    {
        if (isset($this->singletonInstances[$id])) {
            return $this->singletonInstances[$id];
        }

        if (isset($this->requestInstances[$id])) {
            return $this->requestInstances[$id];
        }

        return match ($id) {
            'App\Controllers\UserController' => $this->resolve_App_Controllers_UserController(),
            'App\Middleware\AuthMiddleware' => $this->resolve_App_Middleware_AuthMiddleware(),
            'Psr\Http\Server\MiddlewareInterface' => $this->get('App\Middleware\AuthMiddleware'),
            default => throw new RuntimeException("Service not found: $id"),
        };
    }

    private function resolve_App_Controllers_UserController(): object
    {
        $instance = new \App\Controllers\UserController();
        $this->singletonInstances['App\Controllers\UserController'] = $instance;
        return $instance;
    }

    private function resolve_App_Middleware_AuthMiddleware(): object
    {
        $instance = new \App\Middleware\AuthMiddleware();
        $this->singletonInstances['App\Middleware\AuthMiddleware'] = $instance;
        return $instance;
    }

    public function has(string $id): bool
    {
        return in_array($id, [
            'App\Controllers\UserController',
            'App\Middleware\AuthMiddleware',
            'Psr\Http\Server\MiddlewareInterface',
        ]);
    }

    public function resetScope(string $scope): void
    {
        if ($scope === 'request') {
            $this->requestInstances = [];
        }
    }

    public function runHooks(string $attributeClass): void
    {
        foreach ($this->singletonInstances as $instance) {
            $this->executeHooksOn($instance, $attributeClass);
        }
        foreach ($this->requestInstances as $instance) {
            $this->executeHooksOn($instance, $attributeClass);
        }
    }

    private function executeHooksOn(object $instance, string $attributeClass): void
    {
        $reflection = new ReflectionClass($instance);
        foreach ($reflection->getMethods() as $method) {
            if (!empty($method->getAttributes($attributeClass))) {
                $method->invoke($instance);
            }
        }
    }
}
